### ISSUE TITLE
[BUG] slack run --show-triggers flag lists triggers twice

### ISSUE THREAD

**Issue by NathanHRich** [slackapi/deno-slack-hooks#69]
### Describe the bug
When running a slack app via the `slack run` command, triggers are listed by default.
When the command is run with the `--show-triggers` flag, triggers are listed twice.
If you check the logs, there are two HTTP Requests posted to the `workflows.triggers.list` endpoint

### Requirements (place an `x` in each of the `[ ]`)**
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce
Run `slack run --show-triggers`
Check the logs and you'll see that there are two calls made to list triggers

### Expected behavior
The presence of the --show-triggers flag tells me that triggers shouldn't be shown be default. But they are, so the flag doesn't really do anything useful.

**Comment by filmaj** [comment]
I believe this issue is fixed using the slack CLI v2.5.0 or newer.

**Comment by zimeg** [comment]
Following up to share that version 2.5.0 of the CLI has replaced the `--show-triggers` flag with `--hide-triggers`!

By default, four triggers will be shown on `run` or `deploy` and these can be hidden with `--hide-triggers`. Additional triggers can also be listed with `slack triggers list --limit N`, where `N` is the number of triggers to list.

Really appreciate you raising this issue! Since it has been fixed we can close this issue, but please feel free to follow up with any other feedback or questions!
